// swift-tools-version: 5.9
import PackageDescription

// AI CONTEXT — Package.swift
// SwiftPM manifest used ONLY for the AutohopCore library + the command-line
// smoke-test executables (RSSParserSmoke, OPMLSmoke, SubscriptionStoreSmoke,
// DownloadManagerSmoke, StatsSmoke — run via `swift run <name>`). The iOS app
// itself is built from Autohop.xcodeproj, which is GENERATED by XcodeGen from
// project.yml — edit project.yml, not the xcodeproj. AutohopCore contains the
// UI-independent sources (models, parsing, persistence, stats) shared by the
// app target and the smoke tests.
let package = Package(
    name: "Autohop",
    platforms: [
        // Phase 0 of Docs/TVOS_APP_IMPLEMENTATION_PROPOSAL.md: AutohopCore is
        // the shared library for every Autohop surface. macOS is here only for
        // headless `swift test`; there is no Mac app.
        .iOS(.v17),
        .tvOS(.v17),
        .watchOS(.v10),
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "AutohopCore",
            targets: ["AutohopCore"]
        ),
        .executable(
            name: "RSSParserSmoke",
            targets: ["RSSParserSmoke"]
        ),
        .executable(
            name: "OPMLSmoke",
            targets: ["OPMLSmoke"]
        ),
        .executable(
            name: "SubscriptionStoreSmoke",
            targets: ["SubscriptionStoreSmoke"]
        ),
        .executable(
            name: "DownloadManagerSmoke",
            targets: ["DownloadManagerSmoke"]
        ),
        .executable(
            name: "StatsSmoke",
            targets: ["StatsSmoke"]
        )
    ],
    dependencies: [
        // SQLite layer backing AutohopDatabase (see SYNC_DESIGN.md).
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "6.29.0")
    ],
    targets: [
        .target(
            name: "AutohopCore",
            dependencies: [
                .product(name: "GRDB", package: "GRDB.swift")
            ],
            path: ".",
            exclude: [
                "App",
                ".github",
                ".swiftpm",
                "Chapters",
                "Downloads/DownloadProgressModel.swift",
                "Feeds/FeedPreviewViewModel.swift",
                "Feeds/FeedService.swift",
                "OPMLSmokeTests",
                "Persistence/SettingsStore.swift",
                "Playback",
                "README.md",
                "Scripts",
                "Settings",
                "SmokeTests",
                "SubscriptionStoreSmokeTests",
                "DownloadManagerSmokeTests",
                "StatsSmokeTests",
                "Tests",
                "Views"
            ],
            sources: [
                "Models/Chapter.swift",
                "Models/Subscription.swift",
                "Models/Episode.swift",
                "Models/AppSettings.swift",
                "Models/ListeningHistory.swift",
                "Models/Synced.swift",
                "Models/SyncState.swift",
                "Models/QueueSnapshot.swift",
                "Models/TVProjection.swift",
                "Models/SubscriptionOrder.swift",
                "Models/ArtworkURL.swift",
                "Models/ShareContent.swift",
                "Stats/ShowEngagementAnalyzer.swift",
                "Models/PlaybackPreference.swift",
                "Models/SilenceGapAccounting.swift",
                "Feeds/ParsedFeed.swift",
                "Feeds/RSSParser.swift",
                "Feeds/OPMLService.swift",
                // tvOS Phase 4 (§9 item 1): search + charts + the standalone
                // feed loader are Foundation-only (verified — no UIKit), so
                // they move into the shared library rather than being
                // duplicated for TV. Zero behavior change for iOS; it already
                // compiled these directly.
                "Feeds/PodcastSearch.swift",
                "Feeds/PodcastCharts.swift",
                "Feeds/EpisodeFeedLoader.swift",
                // AppState decomposition Stage 2: the pure refresh planner and
                // history store retain shared-core membership so tvOS and future
                // surfaces compile against one implementation.
                "Feeds/ReleaseRadarCyclePlanner.swift",
                "Persistence/SubscriptionStore.swift",
                "Persistence/AutohopDatabase.swift",
                "Persistence/LockedDeviceFileAccess.swift",
                "Persistence/CloudKitSyncMapping.swift",
                "Persistence/CloudSyncEngine.swift",
                "Persistence/ListeningHistoryStore.swift",
                "Persistence/ListeningStatsStore.swift",
                "Persistence/AutoDownloadIntentStore.swift",
                "Persistence/PlaybackPositionStore.swift",
                "Persistence/SubscriptionSurvivalKit.swift",
                "Persistence/TVProjectionStore.swift",
                "Queue/QueueService.swift",
                "Queue/QueueModel.swift",
                "PlaybackCore/PlaybackControlling.swift",
                "PlaybackCore/PlaybackCapabilities.swift",
                "PlaybackCore/PlaybackSessionPolicy.swift",
                "PlaybackCore/AudioRouteLossPolicy.swift",
                "PlaybackCore/StreamingPlaybackState.swift",
                "PlaybackCore/StreamingPlaybackEngine.swift",
                "Logging/AppLogger.swift",
                "Downloads/DownloadManager.swift",
                "Downloads/DownloadRecoveryPolicy.swift",
                // Autohop Relay client (2026-07-10): zero UIKit dependency
                // (pure Foundation/URLSession/Security), shared so tvOS can
                // register/receive push without duplicating this networking
                // layer. The iOS Xcode target compiles these directly via its
                // own source glob too — they physically stay in Relay/, this
                // just ALSO exposes them to TV's AutohopCore package product.
                "Relay/RelayModels.swift",
                "Relay/RelayCredentialsStore.swift",
                "Relay/RelayClient.swift"
            ]
        ),
        .executableTarget(
            name: "RSSParserSmoke",
            dependencies: ["AutohopCore"],
            path: "SmokeTests",
            resources: [
                .copy("Fixtures")
            ]
        ),
        .executableTarget(
            name: "OPMLSmoke",
            dependencies: ["AutohopCore"],
            path: "OPMLSmokeTests",
            resources: [
                .copy("Fixtures")
            ]
        ),
        .executableTarget(
            name: "SubscriptionStoreSmoke",
            dependencies: ["AutohopCore"],
            path: "SubscriptionStoreSmokeTests"
        ),
        .executableTarget(
            name: "DownloadManagerSmoke",
            dependencies: ["AutohopCore"],
            path: "DownloadManagerSmokeTests"
        ),
        .executableTarget(
            name: "StatsSmoke",
            dependencies: ["AutohopCore"],
            path: "StatsSmokeTests"
        ),
        .testTarget(
            name: "AutohopCoreTests",
            dependencies: ["AutohopCore"],
            path: "Tests",
            exclude: [
                "RSSParserSmokeTest.swift",
                // Widget contract/parser files compile into the iOS app and
                // extension targets, not AutohopCore. Xcode's AutohopTests owns
                // these iOS-only characterizations.
                "WidgetSharedStorageTests.swift",
                "WidgetDeepLinkParserTests.swift"
            ],
            resources: [
                .copy("Fixtures")
            ],
            // Lets shared test files import the AutohopCore library under SwiftPM
            // while still importing the app module under the Xcode test target.
            swiftSettings: [
                .define("AUTOHOP_SPM")
            ]
        )
    ]
)
